<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Account\" />
    <Folder Include="Hrm\RolePrivilege\Queries\" />
    <Folder Include="Medical\Appointment\Queries\" />
    <Folder Include="Medical\PrescriptionDetail\Commands\" />
    <Folder Include="Medical\PrescriptionDetail\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASHT.Domain\ASHT.Domain.csproj" />
    <ProjectReference Include="..\ASHT.Infrastructure\ASHT.Infrastructure.csproj" />
  </ItemGroup>

</Project>
